import type { PncpItem } from './types';

/**
 * Dataset didático para demo do CEO — usado quando o PNCP não retorna nada
 * na janela (fora do horário comercial, instabilidade, feriado, etc.) ou
 * quando o usuário aciona explicitamente o botão "Carregar exemplo".
 *
 * 10 editais realistas: 2 BID, 3 PARCIAL, 3 NO-BID (candidatos) e 2 descartados.
 */
export const DEMO_ITEMS: PncpItem[] = [
  {
    id: 'demo-1',
    numeroControlePNCP: '00000000000000-1-000001/2026',
    objeto: 'Contratação de fábrica de software para sustentação evolutiva de sistemas do Ministério, incluindo squads dedicados (backend, frontend, DevOps, QA) — LC 14.133/21.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Ministério da Gestão e da Inovação em Serviços Públicos',
    unidade: 'Secretaria de Governo Digital', uf: 'DF', municipio: 'Brasília',
    valorEstimado: 18_500_000, dataPublicacao: new Date(Date.now() - 2 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 12 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: true, portaria1070: true, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-2',
    numeroControlePNCP: '00000000000000-1-000002/2026',
    objeto: 'Operação assistida de Service Desk multinível (N1/N2/N3), com atendimento 24x7 e SLAs por severidade, para 12.000 usuários da autarquia — ITIL v4.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'INSS — Instituto Nacional do Seguro Social',
    unidade: 'DTI', uf: 'DF', municipio: 'Brasília',
    valorEstimado: 9_200_000, dataPublicacao: new Date(Date.now() - 1 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 20 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: true, portaria1070: false, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-3',
    numeroControlePNCP: '00000000000000-1-000003/2026',
    objeto: 'Implantação e sustentação de plataforma ITSM/ESM (ServiceNow ou InvGate) com integração ao AD/Entra ID e catálogos automatizados via Power Platform.',
    modalidade: 'Concorrência', modalidadeId: 4,
    orgao: 'Tribunal Regional Federal da 1ª Região',
    uf: 'DF', municipio: 'Brasília',
    valorEstimado: 6_400_000, dataPublicacao: new Date(Date.now() - 3 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 25 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: false, portaria1070: true, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-4',
    numeroControlePNCP: '00000000000000-1-000004/2026',
    objeto: 'Desenvolvimento de agentes de IA generativa (Azure OpenAI + Microsoft Copilot Studio) para automação de fluxos internos e atendimento cidadão.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Serpro',
    uf: 'DF', municipio: 'Brasília',
    valorEstimado: 4_100_000, dataPublicacao: new Date(Date.now() - 4 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 18 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: true, portaria1070: false, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-5',
    numeroControlePNCP: '00000000000000-1-000005/2026',
    objeto: 'Aquisição de licenças perpétuas de software de virtualização (VMware) com suporte 24x7 por 36 meses.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Marinha do Brasil', uf: 'RJ', municipio: 'Rio de Janeiro',
    valorEstimado: 3_800_000, dataPublicacao: new Date(Date.now() - 5 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 15 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: false, portaria1070: false, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-6',
    numeroControlePNCP: '00000000000000-1-000006/2026',
    objeto: 'Contratação de mão de obra terceirizada para suporte técnico de campo (field service) em 42 unidades no interior do estado — 200 postos.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Governo do Estado de São Paulo', uf: 'SP', municipio: 'São Paulo',
    valorEstimado: 12_800_000, dataPublicacao: new Date(Date.now() - 2 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 10 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: false, portaria1070: false, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-7',
    numeroControlePNCP: '00000000000000-1-000007/2026',
    objeto: 'Contratação de solução de backup corporativo em nuvem híbrida com retenção de 7 anos e cifragem AES-256.',
    modalidade: 'Dispensa', modalidadeId: 8,
    orgao: 'Prefeitura Municipal de Fortaleza', uf: 'CE', municipio: 'Fortaleza',
    valorEstimado: 780_000, dataPublicacao: new Date(Date.now() - 6 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 7 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: false, portaria1070: false, lei14133: true },
    status: 'candidate',
  },
  {
    id: 'demo-8',
    numeroControlePNCP: '00000000000000-1-000008/2026',
    objeto: 'Contratação de squad de dados (engenharia + analytics) para modernização do BI corporativo em Power BI / Fabric.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Petrobras', uf: 'RJ', municipio: 'Rio de Janeiro',
    valorEstimado: 5_600_000, dataPublicacao: new Date(Date.now() - 1 * 864e5).toISOString(),
    dataAbertura: new Date(Date.now() + 22 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: true, portaria750: true, portaria1070: true, lei14133: true },
    status: 'candidate',
  },
  // ── Descartados ───────────────────────────────────────────────────────────
  {
    id: 'demo-9',
    numeroControlePNCP: '00000000000000-1-000009/2026',
    objeto: 'Aquisição de gêneros alimentícios para merenda escolar — hortifruti e proteína animal.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'Secretaria de Educação do DF', uf: 'DF', municipio: 'Brasília',
    valorEstimado: 2_100_000, dataPublicacao: new Date(Date.now() - 3 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: false, portaria750: false, portaria1070: false, lei14133: true },
    status: 'discarded',
    motivos_descarte: ['blacklist:alimentos', 'fora_de_ti'],
  },
  {
    id: 'demo-10',
    numeroControlePNCP: '00000000000000-1-000010/2026',
    objeto: 'Serviço de vigilância armada patrimonial para as instalações do órgão.',
    modalidade: 'Pregão Eletrônico', modalidadeId: 6,
    orgao: 'IFRN', uf: 'RN', municipio: 'Natal',
    valorEstimado: 3_400_000, dataPublicacao: new Date(Date.now() - 4 * 864e5).toISOString(),
    linkSistemaOrigem: 'https://pncp.gov.br',
    aderencia: { ti: false, portaria750: false, portaria1070: false, lei14133: true },
    status: 'discarded',
    motivos_descarte: ['blacklist:vigilância armada', 'fora_de_ti'],
  },
];

export const DEMO_META = {
  total_bruto: 312,
  candidatos: DEMO_ITEMS.filter((i) => i.status !== 'discarded').length,
  descartados: DEMO_ITEMS.filter((i) => i.status === 'discarded').length + 42,
  descartados_blacklist: 22,
  descartados_fora_ti: 18,
  descartados_valor: 4,
  totalRegistros: 312,
  intervalo: { de: '—', ate: '—' },
  modalidades: [6, 4],
  valorMinimo: 50000,
  blacklistAplicada: 51,
  paginasPorModalidade: 3,
  demo: true,
};
